### ISSUE TITLE
build release android package size 50MB and request down crosswalk

### ISSUE THREAD

**Issue by edispro** [mendix/hybrid-app-base#20]
build release android package size 50MB and request down crosswalk
![screenshot_25601020_120641](https://user-images.githubusercontent.com/14953314/31806198-7196ad0c-b590-11e7-8327-e6f4220eab64.jpg)

**Comment by KevinVlaanderen** [comment]
In recent releases of the hybrid app, Crosswalk is disabled by default. The Crosswalk project has long been discontinued, as there is no need for it anymore on devices running Android 4.4+. Is it possible for you to move to a newer version of the hybrid app and/or disable Crosswalk?

**Comment by smarki** [comment]
Closing it as the platform itself does not support 4.4 or lower anymore for new builds.
