### ISSUE TITLE
Online app default timeout of 5 second is causing client exception in the app

### ISSUE THREAD

**Issue by romilgaurav** [mendix/hybrid-app-base#31]
Hi, the timeout in the app is changed to 5 seconds now.

https://github.com/mendix/hybrid-app-base/blob/master/src/www/scripts/app.js line 152
server: {
                    timeout: enableOffline ? 30000 : 5000
            },

Can this be increased to 30000 again? This will cause issue if the request is taking longer time or if we are uploding document of larger time.
I have to build custom app every time and it fails many times in the process. Also, custom build causes other unwanted issues in the app.

**Comment by KevinVlaanderen** [comment]
Hi there.

That is actually not what we changed. The timeout used to be 5000 (5s) in all cases. We extended the period for offline apps, where more data needs to be uploaded.
We are not comfortable with changing the timeout for all apps by default. In case there actually is a connection issue, the user would only get feedback after 30 seconds, instead of 5.

Perhaps it's better if we try and address the issues you're running into. Can you share some more details, please?

Cheers,

Kevin

**Comment by romilgaurav** [comment]
++ Rob Bond

Hi Kevin,

We have Hybrid app on Mendix, and we are calling few APIs in the app which take more than 10 seconds to respond. Also, we are having feature where we use camera to upload image to the app. Whenever it takes more than 5 seconds, we get connection error from client.
[cid:image001.png@01D42D77.B1A6E510]

If we increase the timeout in entry.js to 30 seconds, this error stops coming.

// Increase the timeout
    dojoConfig.server.timeout = 30000;

But this cause new issue

1.       the built app now always points to production environment.

2.       I always have to do a custom build to increase the timeout.

We do not use offline features of the app. So while building, I don’t select “offline features” in Mendix home website.

Is there a way to increase default timeout of the app?

Thanks,

Romil Gaurav
Software Engineer, Home Services, Sears Holdings Corporation
Cell - +1 224 201 9944

**Comment by MulderWH** [comment]
Hi Romil, what unwanted issues do you get when using custom builds?

**Comment by romilgaurav** [comment]
The only issue I am getting now is that the custom build always point to prod environment. I am yet to explore more issues, but for now this is the only issue. We need to create app from accep and test environment too.

**Comment by MulderWH** [comment]
For that you can setup the environments.json file in the config folder, i.e.
{
  "test" : {
    "name" : "My App",
    "identifier" : "io.mxapps.myapp",
    "url" : "https://myapp-test.mxapps.io"
  },
  "acceptance" : {
    "name" : "My App",
    "identifier" : "io.mxapps.myapp",
    "url" : "https://myapp-accp.mxapps.io"
  },
  "production" : {
    "name" : "My App",
    "identifier" : "io.mxapps.myapp",
    "url" : "https://myapp.mxapps.io"
  }
}

**Comment by romilgaurav** [comment]
Thanks. This worked.

Regards,

Romil

**Comment by MulderWH** [comment]
Cool. For the camera widget it's a best practice to change the image quality. If you do not change the default values of the widget, then you get the full sized picture of the mobile device. However in most use cases there's no need to. For example we have changed ours to 500 pixels, which is perfect for a profile pic scenario;-)
