### ISSUE TITLE
npm run package fails for new builds

### ISSUE THREAD

**Issue by Mcpoowl** [mendix/hybrid-app-base#36]
Hi guys,

I think this has something to do with the new PushNotifications release, but when I try to `npm run package` on a newly created package, I get an error about missing files in my .node-modules.

1. Create package from Mendix Portal
2. Unpack, open powershell in that location
3. `npm install`
4. `npm run package`

![image](https://user-images.githubusercontent.com/2244753/50757301-239a0400-125f-11e9-98dc-bd4335560163.png)

**Comment by KevinVlaanderen** [comment]
Hi Paul. Thanks for the report. The build-extras.gradle file indeed wasn't included properly in the npm and portal packages (third error in the screenshot). We've released a new version of the base package. Can you please try again (or use e.g. npm update in your current project folder).

Please note that the first two issues are related to a new requirement for the push notifications plugin. If your app used Push Notifications, you should provide these two files (which you can obtain by creating a Firebase app). If you do not use Push Notifications, you should turn of Push Notifications when exporting your package from the Portal (or set 'push' to false in config/parameters.json).

**Comment by Mcpoowl** [comment]
Hi Kevin,

Thanks for your swift reply. Updating and running again solves that one issue indeed. The other two are on me for not adding the .plist file.

Thanks!
